// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trjwlvfcduglwprstips.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyandsdmZjZHVnbHdwcnN0aXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzQwNzAsImV4cCI6MjA3MjMxMDA3MH0.8hltaI8mh3NiV2Q2iIy5YC-t_aMmhMuocIQSDxZmvPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});